language: node_js
node_js:
  - "node"
  - "7"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  directories:
    - node_modules
    - client/node_modules
before_script: 
  - cd client
  - npm install
  - npm run build
  - cd ../server
  - npm install
script: 
　-  cd client && npm run test
  -  cd server && npm run test