sudo: false
language: node_js
node_js:
  - '6'
cache:
  directories:
    - node_modules
    - client/node_modules
install:
  - npm i npminstall && npminstall
before_script:
  - npm install 
  - cd client
  - npm install
  - npm run build
script: npm run test && cd .. && npm run ci
after_script:
  - npminstall codecov && codecov
