language: node_js
node_js:
  - "node"
  - "7"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  directories:
    - node_modules
before_script: 
  - npm install
  - npm run build
script: npm run test