export const LOAD_MEMOS = 'LOAD_MEMOS';

export const LOADING_MEMOS = 'LOADING_MEMOS';

export const SAVING_MEMOS = 'SAVING_MEMOS';

export const SAVE_MEMOS = 'SAVE_MEMOS';

export const ADD_MEMO = 'ADD_MEMO';

export const EDIT_MEMO = "EDIT_MEMO";

export const EDIT_MEMODETAIL = "EDIT_MEMODETAIL";

export const DELETE_MEMO = 'DELETE_MEMO';

export const TOGGLE_COMPLETE = 'TOGGLE_COMPLETE';

export const SEARCH_MEMO = 'SEARCH_MEMO';

export const FILTER_COMPLETED = 'FILTER_COMPLETE';

export const FILTER_UNCOMPLETED = 'FILTER_UNCOMPLETE';

export const FILTER_ALL = 'FILTER_ALL'

export const SUCCESS_LOAD_MEMOS='SUCCESS_LOAD_MEMOS';

export const FAIL_LOAD_MEMOS = 'FAIL_LOAD_MEMOS';

export const SUCCESS_SAVE_MEMOS = 'SUCCESS_SAVE_MEMOS';

export const FAIL_SAVE_MEMOS = 'FAIL_SAVE_MEMOS';


